### ISSUE TITLE
Add a combat system

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/Vehicle-Building-Game#3]
### Description
The groundwork for vehicle on vehicle warfare

### Tasks
- [x] Motion system, for kinetic damage calculations
- [x] A way to spawn in npc vehicles
- [x] Remove cannon weapon, replace with mouseless alternatives 
- [x] A spike with high melee damage
- [x] #4
