### ISSUE TITLE
MAJOR RELEASE: 1.2.0 sandbox mode and UI improvements

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/Vehicle-Building-Game#53]
## Description
The 2nd major update to the game, introduces sandbox mode and far better visuals ([see figma design](https://www.figma.com/file/ecuOe9utC0niBbYC9IWZAo/Untitled?type=design&node-id=0-1&mode=design&t=Iu9oNG2CflZCqlVz-0))

## Tasks
- [x] Revamp home screen
- [x] Redesign login to work as a popup
- [x] Design and build a better looking change dashboard
- [x] Redo in game UI
- [x] Remake level selector menu
- [x] #28 
- [x] #5
