### ISSUE TITLE
Full Mobile Support

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/Vehicle-Building-Game#70]
Make the game fully mobile compatible 
## Tasks
- [x] Make everything smaller on mobile so the sizing looks good
- [ ] Remake all mobile buttons, with some on the right and some on the left for easy control
- [ ] Include tutorial for Mobile
