### ISSUE TITLE
Bosses 

### ISSUE THREAD

**Issue by BSchoolland** [BSchoolland/Vehicle-Building-Game#83]
# Tasks
- [x] Allow users to collect items to help with the boss fight at the end of each world
- [x] Prevent players from progressing to the next world until beating the boss
- [x] Boss for world 2
- [x] Boss for world 3
- [ ] Boss for world 4
- [x] Different music when fighting bosses
